### ISSUE TITLE
Sending test alert notification failed with message: Could not send message to Slack.

### ISSUE THREAD

**Issue by NewEvolution** [Graylog2/graylog-plugin-slack#42]
I'm receiving an error toast in Graylog stating "Sending test alert notification failed with message: Could not send message to Slack." when clicking the test button on a Slack notification.

Using curl to post JSON to the Slack webhook URL used in the plugin works as expected.

Tailing graylog's `server.log` shows no output whatsoever happening when the button is clicked and the toast appears.

Anywhere else I can look to find what could be causing the error message/the test alert not to send?

**Comment by NewEvolution** [comment]
Switched output to another channel and it started working. 👻

**Comment by rdhand-wish** [comment]
I am having the same issue after Slack plugin worked for a while. Unfortunately I am not in a position to switch to new slack channel. Is there any way to fix this issue?

**Comment by Aenima4six2** [comment]
@rdhandwish Fixing the issue depends on where the problem lies. I'm skeptical at this point its the plugin, but I'm happy to further diagnose if you can provide some additional information. 

1. Slack Plugin Version
2. Base web hook URI you are using
3. Alert configuration you are testing with.
4. Graylog version.
5. Errors or stack traces produced in logs.

**Comment by rdhand-wish** [comment]
Thank you for the update. The issue seems to be with Slack. When the admin who created the private Slack channel leaves the channel, alerts stop going to the channel. When the admin is re-invited back to the Slack channel, alerts start showing up as normal.
